# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZ3XSccIjrHsXG8C47pxi1L9CzyF86SW
"""

print("Hello vasek")

for i in range(10,150):
    if i % 15 == 0:
        print(i)
    elif i % 5 == 0:
        print(i)